version: '3.8'

services:
  app:
    build: .
    container_name: hsr-app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "8090:8090"
    restart: unless-stopped