### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/api/v1/calculator/calculate/manual
Content-Type: application/json

{
  "character": {
    "name": "클라라",
    "level": 80,
    "baseHp": 2406,
    "baseAtk": 1319,
    "baseDef": 882,
    "spd": 90,
    "scalingAttribute": "ATK",
    "element": "PHYSICAL",
    "fatePath": "DESTRUCTION",
    "basicAttack": {
      "skillMultiplier": 1,
      "extraMultiplier": 0,
      "extraDamage": 0
    },
    "skill": {
      "effectType": "DAMAGE",
      "skillMultiplier": 1.26,
      "extraMultiplier": 0,
      "extraDamage": 0
    },
    "ultimate": {
      "effectType": "BUFF"
    }
  },
  "enemy": {
    "name": "테스트 적",
    "level": 74,
    "baseHp": 5000,
    "baseDef": 940,
    "weaknessElements": ["ICE", "WIND", "IMAGINARY"],
    "resistanceElements": ["FIRE"],
    "isBroken": false
  },
  "characterBuffs": {
    "buffs": [
      {"buffType": "PHYSICAL_DAMAGE_BOOST", "buffValue": 14.4},
      {"buffType": "ATK_PERCENT", "buffValue": 24.0},
      {"buffType": "ATK_PERCENT", "buffValue": 28.0},
      {"buffType": "ATK_PERCENT", "buffValue": 12.0},
      {"buffType": "ATK_PERCENT", "buffValue": 12.0},
      {"buffType": "DAMAGE_BOOST", "buffValue": 45.0},
      {"buffType": "RES_PEN", "buffValue": 24.0},
      {"buffType": "CRIT_RATE_PERCENT", "buffValue": 20.0},
      {"buffType": "CRIT_DMG_PERCENT", "buffValue": 48.0},
      {"buffType": "CRIT_DMG_PERCENT", "buffValue": 18.0}
    ]
  },
  "enemyBuffs": {
    "buffs": [
      {"buffType": "DEF_REDUCTION", "buffValue": 8.0},
      {"buffType": "DEF_REDUCTION", "buffValue": 16.0},
      {"buffType": "DAMAGE_TAKEN_INCREASE", "buffValue": 40.0}
    ]
  }
}